[package]
name = "rust-async-graphql-parser"
version = "0.1.0"
authors = ["starptech <deusdustin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.10"
async-graphql-parser = "2.9.10"